apiVersion: v1
kind: Service
metadata:
  name: warehouseapi-service
spec:
  type: NodePort
  selector:
    app: warehouseapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5221
      nodePort: 30002