apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: postgres
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432