apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderapi
  template:
    metadata:
      labels:
        app: orderapi
    spec:
      containers:
      - name: orderapi-orderapi-1
        image: orderapi:latest
        ports:
        - containerPort: 6020
        imagePullPolicy: IfNotPresent
        env:
        - name: ConnectionStrings__DefaultConnection
          value: "Host=postgres-postgresql.postgres.svc.cluster.local;Port=5432;Database=postgres;Username=postgres;Password=postgres"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: RabbitMQ__Hostname
          value: "rabbitmq.rabbitmq.svc.cluster.local"  
        - name: RabbitMQ__UserName
          value: "guest"            
        - name: RabbitMQ__Password
          value: "guest"
        - name: RabbitMq__QueueName
          value: "queueOrder1"            