apiVersion: v1
kind: Service
metadata:
  name: orderapi-service
spec:
  type: NodePort
  selector:
    app: orderapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6020
      nodePort: 30001